- name: Create a ext4 filesystem on the attached volume
  community.general.filesystem:
    fstype: ext4
    dev: "{{ item.var_vol_mountpoint }}"
  with_items: "{{ instance_create.results }}"

- name: Create a mountpoint for the volume
  ansible.builtin.file:
    path: /dev/sdb
    mode: '0755'
    state: 'directory'

- name: Mount the volume
  ansible.posix.mount:
    path: /dev/sdb
    src: "{{ item.var_vol_mountpoint }}"
    fstype: ext4
    state: present
    with_items: "{{ instance_create.results }}"
