- name: Create a Linode for osd
  linode.cloud.instance:
    label: "{{ resource_prefix }}-osd"
    type: g6-standard-2
    region: "{{ region }}"
    image: "{{ image }}"
    private_ip: true
    authorized_keys:
      - "{{ key_pair.public_key }}"
    wait: false
    state: present
  register: ceph_osd_create

- name: Wait for SSH
  wait_for: host="{{ item.instance.ipv4[0] }}" port=22 timeout=300
  with_items: "{{ ceph_osd_create }}"