- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_output_path }}"
  register: key_pair

- ansible.builtin.include_tasks: instances.yml
- ansible.builtin.include_tasks: volume.yml

# - name: Print all available facts
#   ansible.builtin.debug:
#     var: hostvars[inventory_hostname]

- name: Add instance to inventory
  ansible.builtin.add_host:
    name: "{{ item.instance.ipv4[0] }}"
    groups: hosts_ceph
    var_vol_mountpoint: "{{ item.volume.filesystem_path }}"
  with_items: "{{ volume_create.results }}"
