- name: Create and attach a volume to the osd
  linode.cloud.volume:
    label: "{{ item.instance.label }}-vol"
    region: "{{ region }}"
    size: "{{ ods_volume_size }}"
    linode_id: "{{ item.instance.id }}"
    state: present
  register: volume_create
  loop: "{{ instance_create.results }}"
