name: Lind the Ansible playbook

on:
  push:

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Ansible-lint
        run: |
          pip install ansible-lint
          ansible-galaxy install -r requirements.yml
          ansible-lint --version
          ansible-lint deploy.yml